import RoutListing from "@/components/Items/RoutListing";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Hướng dẫn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-wrap md:flex-nowrap">
      <RoutListing currentPath="guides" title="Hướng dẫn" defaultR="" />
      {children}
    </div>
  );
}
