import RoutListing from "@/components/Items/RoutListing";
import http from "@/utils/http";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
const getData = async () => {
  const res = await http.get("Category/GetAll/Tin tức");
  return res.data;
};
export const metadata: Metadata = {
  title: "Hướng dẫn",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data: { categoryName: string; categoryId: number }[] = await getData();

  return (
    <div className="flex flex-wrap ">
      <RoutListing
        currentPath="guides"
        title="Hướng dẫn"
        defaultR=""
        cate={data.map((r) => ({
          categoryId: r.categoryId,
          categoryName: r.categoryName,
        }))}
      />
      {children}
    </div>
  );
}
