import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FaPhone } from "react-icons/fa6";
import Link from "next/link";
import dynamic from "next/dynamic";

const Header = dynamic(() => import("@/components/Header"));
const Footer = dynamic(() => import("@/components/Footer"));
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trang chủ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full 2xl:w-[1519px]">
          <Header />
          {children}
          <Footer />
          <a
            href="tel:0974034981"
            className="fixed bottom-5 left-2 flex items-center cursor-pointer"
          >
            <div className="w-[50px] h-[50px] rounded-full bg-[#5BB006] flex items-center justify-center z-10 text-white">
              <FaPhone />
            </div>
            <h3 className="text-[15px]  bg-[#0099e6] rounded-[20px] font-semibold py-1 px-[11px] pl-[34px] relative right-[29px] text-white">
              0974034981
            </h3>
          </a>
          <Link
            href="/admin"
            className="fixed bottom-5 right-2 flex items-center  cursor-pointer"
          >
            <h3 className="text-[15px] text-center bg-[#0099e6] rounded-[20px] font-semibold py-1 px-[11px]  text-white">
              Admin
            </h3>
          </Link>
        </div>
      </body>
    </html>
  );
}
