import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { FaPhone } from "react-icons/fa6";
import http from "@/utils/http";
import dynamic from "next/dynamic";
import RoutFull from "@/components/RoutFull";

export const metadata: Metadata = {
  title: "Tin tức",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-wrap">
      <RoutFull />
      {children}
    </div>
  );
}
