import type { Metadata } from "next";
import RoutFull from "@/components/RoutFull";

export const metadata: Metadata = {
  title: "Tin tức",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-wrap">
      <RoutFull />
      {children}
    </div>
  );
}
