import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { FaPhone } from "react-icons/fa6";
import RoutListing from "@/components/Items/RoutListing";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tin tức",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex">
      <RoutListing />
      {children}
    </div>
  );
}
