import http from "@/utils/http";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";

const RoutListing = dynamic(() => import("@/components/Items/RoutListing"));
export const metadata: Metadata = {
  title: "Sản phẩm",
  description: "Generated by create next app",
};
const getData = async () => {
  const res = await http.get("Category/GetAll/Sản phẩm");
  return res.data;
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data: { categoryName: string; categoryId: number }[] = await getData();
  console.log("producc", data);

  return (
    <div className="flex flex-wrap">
      <RoutListing
        currentPath="products"
        title="Sản phẩm"
        defaultR=""
        cate={data.map((r) => ({
          categoryId: r.categoryId,
          categoryName: r.categoryName,
        }))}
      />
      {children}
    </div>
  );
}
