import RoutListing from "@/components/Items/RoutListing";
import http from "@/utils/http";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Sản phẩm",
  description: "Generated by create next app",
};
const getData = async () => {
  const res = await http.get("Category/GetAll/Sản phẩm");
  return res.data;
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data: { categoryName: string }[] = await getData();
  return (
    <div className="flex flex-wrap">
      <RoutListing
        currentPath="products"
        title="Sản phẩm"
        defaultR=""
        cate={data.map((r) => r.categoryName)}
      />
      {children}
    </div>
  );
}
