import http from "@/utils/http";
import type { Metadata } from "next";
import dynamic from "next/dynamic";

const RoutListing = dynamic(() => import("@/components/Items/RoutListing"));
export const metadata: Metadata = {
  title: "Sản phẩm",
  description: "Generated by create next app",
};
const getData = async () => {
  const resT = await http.get("CategoryType/GetAll");
  const res = await http.get<{ categoryName: string; categoryId: number }[]>(
    `Category/GetAll/${resT.data[0].name}`
  );
  const newData = res.data.map((r) => ({
    categoryId: r.categoryId,
    categoryName: r.categoryName,
  }));
  newData.push({
    categoryId: 9999,
    categoryName: "Đã xem",
  });
  return newData;
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await getData();

  return (
    <div className="flex flex-wrap">
      <RoutListing
        currentPath="Sản phẩm"
        title="Sản phẩm"
        category="product"
        defaultR={data[0].categoryName}
        cate={data}
      />
      {children}
    </div>
  );
}
